import = ["~/.config/alacritty/themes/alacritty-theme/themes/noctis-lux.toml"]

[font]
size = 9

[font.normal]
family = "Hack Nerd Font"

[window]
opacity = 0.95
decorations = "none"

[window.padding]
x = 7
y = 0
