#! /bin/sh
#
##! /bin/sh
## STARTUP ##

pipewire&
picom -b &
sxhkd &
nitrogen --restore
$HOME/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr & 

bspc monitor -d 1 2 3


## WINDOW CONFIGUARTION ##


bspc config border_width        0
bspc config window_gap          5 

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true



#### BSPWM COLORING ####


bspc config normal_border_color         "#51576d"
bspc config active_border_color         "#d5a4b5"
bspc config focused_border_color        "#d5a4b5"
bspc config presel_feedback_color       "#d5a4b5"
bspc config urgent_border_color         "#d5a4b5"



## APPLICATION RULES ##
bspc rule -a Gpick state=floating
bspc rule -a Thunar state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Nitrogen state=tiled

